services:
  ros2:
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: ros2_humble_dev

    network_mode: host
    ipc: host

    privileged: true

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    volumes:
      - ./src:/workspace/src
      - /tmp/.X11-unix:/tmp/.X11-unix

    stdin_open: true
    tty: true

    working_dir: /workspace